### ISSUE TITLE
Client Offline Won't Work

### ISSUE THREAD

**Issue by to4ooo4** [gamejolt/gamejolt#103]
On the product page for the client, it said it supports Offline Mode. But when the GameJolt Client is opened without internet, it gets stuck and clicking on the Game Library icon or via the burger menu on the top left doesn't load anything.

**Comment by YLivay** [comment]
yup, we're working on it in #116 
in the future please open issues on our [issue tracker](https://github.com/gamejolt/issue-tracker/issues) instead. We don't usually check this repo for user submitted issues, hence  the super late response :(

**Comment by to4ooo4** [comment]
Ah; my bad.
