### ISSUE TITLE
hi, major issue on gamejolt with staffing

### ISSUE THREAD

**Issue by REALHaydenGaming** [gamejolt/gamejolt#1045]
**I typed this in, unbiastory, observed, and actually see what people do. I wrote this here, because *you never respond to my personal emails.***

Ok, so yes, I have been BANNED [and FALSELY]. But, there IS a problem with me seeing people being banned;

There are some people that have been falsely banned. And the rule "We have evidence "against you"" is basically just a gatekeep from help. I have seen a user getting banned for no reason at all, and you literally IP Banned him, but, what's even worse is that he didn't even do anything WRONG. 

A bully [sic] had mass harassed him both privately, and publically. But you decided to ban him, and that rule named "We have evidence "against you"" gatekeep him from appealing, causing HIM to ban evade. And what's even worse is that I have seen NOBODY get unbanned from here, rendering the fact: If you give an unbias reason as you were BANNED. We won't help YOU. 

And how was I banned falsely? Because I was mass harassed by a user that was banned now. They kept mass reporting my posts, harassed me, and even got me timed out for NO. REASON. (@/ferozdev, he has also got people timed out for no reason. He also said the N Word once.). But I had tried contacting you so many TIMES. And you wouldn't even give me a proper explanation or even proof [and you didn't even show me proof of what I did was wrong].

And the thing I have been observing is that there are so much UNDERAGED, racist, and heck, even ZOOPHILES.

A good example was a recent drama about a user who was being racist, decided to block him over his race.

![Proof for racism on this site](https://user-images.githubusercontent.com/107285739/206876504-548560b6-7196-4e16-92c6-a13df278fcbb.png)

Proof of people using slurs for usernames & posts.
![Proof of people using slurs as there username and posts](https://user-images.githubusercontent.com/107285739/206879663-0ad7f2b2-ddd1-40f8-9cfc-fa8431473ca3.png)

I am very aware he has been banned, but you didn't do anything about it unless they literally, had to. I can NOT say why. Mass report him. It's because YOU, YOU staff members here, don't care about the users here.

What do I mean by this? Allowing Underaged users on the site, these images are not inspect elemented.

![Screenshot 2022-12-10 6 53 11 PM](https://user-images.githubusercontent.com/107285739/206880021-11baab21-0fc4-40e7-892b-181717db30bf.png)
![Screenshot 2022-12-10 6 55 43 PM](https://user-images.githubusercontent.com/107285739/206880024-88509eb0-b95e-4310-a077-ed0adf529eeb.png)
(both to this day HAVE NOT been banned.)

So its already breaking Coppa. AND BOTH of them didn't get help to make it (well like 87% of underaged users don't get help to make it). 

I will edit this later, because I am very tired, of BOTH the STAFF being irresponsible, AND them not doing ANYTHING about it.

**Comment by nilsgj** [comment]
This repository is for the frontend code of Game Jolt, for any issues with content on the service itself send an email to contact@gamejolt.com.

**Comment by FruitloopMonster** [comment]
jose reference lmao
