### ISSUE TITLE
Forum topic move requests

### ISSUE THREAD

**Issue by niksudan** [gamejolt/gamejolt#11]
Moderators for one channel can request to move a topic to another channel. Moderators of the other channel would have to approve it.

Future feature.

**Comment by Tricky1975** [comment]
Perhaps to enhance this feature, if for example I move a thread to another channel I happen to moderate myself as well, perhaps I should then be able to skip the approval step (as I would otherwise have to approve my own request).

**Comment by NikSudan** [comment]
What would happen if another moderator disagrees with your move request? Or maybe there is one user designated to that responsibility? I still think there should be a request because we're wanting to make the channels their own communities.

**Comment by Tricky1975** [comment]
Yeah, I understood that part, my suggestion was only about the when the original channel and the target channel are both moderated/owned by the same person, who would in that case have to approve his own requests.
