### ISSUE TITLE
Media will not show up on post page.

### ISSUE THREAD

**Issue by TheCrafters001** [gamejolt/gamejolt#1111]
#1104 added the ability to add backgrounds to media posts. However there is a bug where viewing the post itself will not show the media.
Example:
![image](https://user-images.githubusercontent.com/46639269/224394212-4902b1e7-d4ca-46d7-af27-7bd2847b86ac.png)
![image](https://user-images.githubusercontent.com/46639269/224394143-24e87793-1a30-4578-9668-1dc8907bdeea.png)
Same post, but the media will not show up by actually visiting the post. You can see the example post [here](https://gamejolt.com/p/eiyrimvp). It could be a page caching thing, but clearing the cache doesn't seem to do anything.

**Comment by nilsgj** [comment]
Hey, thanks for reporting. We are aware of this issue and are preparing a fix for it.

**Comment by nilsgj** [comment]
Fixed with https://github.com/gamejolt/gamejolt/commit/cdae20c4352a40358dab2f88057e163e0b9a090b
