### ISSUE TITLE
rename joltron executable names

### ISSUE THREAD

**Issue by YLivay** [gamejolt/gamejolt#123]
people are rightfully wary of the random joltron.exe prompt that pops up when you first launch the client with joltron.

* should look into detection when joltron is NOT given permission and direct people how to unblock it when it happens

**Comment by YLivay** [comment]
depends  on  #131

**Comment by hworld** [comment]
we decided not to do this since it doesn't pop up a warning anymore?

**Comment by YLivay** [comment]
Yeah, once we push the new joltron it'll be fixed
