### ISSUE TITLE
client updates using new nwjs snappy updater

### ISSUE THREAD

**Issue by YLivay** [gamejolt/gamejolt#131]
got rid of babel and all those memes, and we might need to do something clever to update joltron's binaries.
since they are included in client-voodoo as binaries, when nwjs snappy updater attempts to rename and delete the old node modules it will fail if games are running (on windows only afaik).

We might need to tell nwjs which files specifically should be deleted, or do a more generic approach of instead renaming node modules to .old and removing - to rename them to some random temp name under a "graveyard" directory that the client will attempt to delete periodically. This will allow us to fail gracefully if the old node modules fail to be swapped out since renames at least DO work.

**Comment by hworld** [comment]
Can we just not do the update while a game is running?

**Comment by YLivay** [comment]
Nope, still gotta do it, client also uses joltron for holding the mutex so it might be in use either way.
we'll need a one time hook to go through with updating the client properly too.

**Comment by YLivay** [comment]
done
