### ISSUE TITLE
Forum information in profile

### ISSUE THREAD

**Issue by niksudan** [gamejolt/gamejolt#16]
This was suggested for the previous forum as a feature. I think it's a pretty cool idea, but I'm not sure if people would want their forum activity on their user profile.

This way you could see what topics other users are following as well as topics they have started - you aren't just limited to your own account. But then there's the question of the privacy or not.

**Comment by Tricky1975** [comment]
I'm basically all for it, but I think if we can just set it to "HIDE" in our personal settings we can decide for ourselves if we want to share this or not. 

You may also put it like this

Show community information to:
- (*) Everybody
- ( ) Friends only
- ( ) Nobody


Perhaps in the case of "nobody" it may still be a good idea if staff members can still see it for moderation purposes, but I'll leave that up to you. This way, members can decide for themselves if they got no secrets or if they value their privacy.
