### ISSUE TITLE
Gotta sync all game/package data again.

### ISSUE THREAD

**Issue by hworld** [gamejolt/gamejolt#166]
Needed since the thumbnail media item has changed in the local db. Needs to get the fresh model to populate or it doesn't show the thumbnail.

We need a way to tell the server to return all data in certain scenarios, but I'm worried about the load on the server when we push an update that does this then...

**Comment by YLivay** [comment]
works, but offline mode doesn't. not sure yet if a bug or a development configuration issue. will open a new issue if that's the case.
