### ISSUE TITLE
Internal Server Error

### ISSUE THREAD

**Issue by shmellyorc** [gamejolt/gamejolt#198]
It has been almost a week and still getting "internal server error" on your website. I am using windows 10 april update using chrome 67.0.3396.87 (Official Build) (64-bit).

I have also ran chrome in incognito and I get the same result.

![image](https://user-images.githubusercontent.com/5901214/41394443-cc7c4df2-6f5e-11e8-8cad-6c7a1d12647a.png)

**Comment by shmellyorc** [comment]
Lastly, I just reinstalled windows 10 and I am still getting the same issue.

**Comment by shmellyorc** [comment]
when going to https://gamejolt.com from chrome address bar I get this: 
![image](https://user-images.githubusercontent.com/5901214/41442147-a15cdeac-6fea-11e8-81a2-83e4ce31910f.png)

refresh:
![image](https://user-images.githubusercontent.com/5901214/41442185-cc82d65e-6fea-11e8-9e44-5caa93198dcc.png)
![image](https://user-images.githubusercontent.com/5901214/41442208-e9f13f64-6fea-11e8-8b5d-1991556b57d1.png)

**Comment by shmellyorc** [comment]
lastly chrome network, this might be useful:
![image](https://user-images.githubusercontent.com/5901214/41442291-593c0dd6-6feb-11e8-8641-31bda36d8e37.png)

**Comment by shmellyorc** [comment]
make the console to show everything and got this:
![image](https://user-images.githubusercontent.com/5901214/41442449-1c5acae6-6fec-11e8-9047-fa007cdbb185.png)

**Comment by shmellyorc** [comment]
I cleared the console before switching to another page like gamejolt.com/learn or */login:
![image](https://user-images.githubusercontent.com/5901214/41442895-79a29d08-6fee-11e8-94ff-35da3402b067.png)

**Comment by shmellyorc** [comment]
Lastly grabbed the error from line 91:

message
:
"error is not defined"
stack
:
"ReferenceError: error is not defined↵    at eval (eval at <anonymous> (https://s.gjcdn.net/app.app.d9c3a9.js:1:440348), <anonymous>:1:1)↵    at Function.<anonymous> (https://s.gjcdn.net/app.app.d9c3a9.js:1:440348)↵    at r (https://s.gjcdn.net/app.vendor.64a1a6.js:21:48068)↵    at Object.next (https://s.gjcdn.net/app.vendor.64a1a6.js:21:47403)↵    at i (https://s.gjcdn.net/app.vendor.64a1a6.js:21:47170)"

**Comment by shmellyorc** [comment]
Can access your site again <3. Can finally update my game. thanks.

**Comment by hworld** [comment]
Yay! Glad it's working for you now. =]
