### ISSUE TITLE
Source preview not right

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/gamejolt#29]
Source preview not right, if you ask me:

![image](https://cloud.githubusercontent.com/assets/11202073/12920765/39e4087e-cf4a-11e5-9a34-33d1d6fee617.png)

**Comment by Tricky1975** [comment]
Not to sound like a jerk, but it still happened to me.

**Comment by hworld** [comment]
That's because I haven't pushed out the new build yet.

**Comment by Tricky1975** [comment]
Okay.... XD
