### ISSUE TITLE
Apple Quarantines Apps (so retrieving .gj-credentials is nearly impossible)

### ISSUE THREAD

**Issue by alexis-evelyn** [gamejolt/gamejolt#309]

**Comment by SenorContento** [comment]
Signing the app and hardening it does not prevent the Translocation issue (being opened in a separate folder). I will have to see if there is something I can add to my entitlements file that will keep the app from being quarantined.

**Comment by SenorContento** [comment]
I have been researching and there is nothing I can do to prevent my app from being quarantined. This is just a state of how quarantine works, however, you can add an entry to your entitlements file to prevent the quarantine flag from being set on downloaded apps.

I decided to download other Mac games to see if they handle the quarantine properly. Out of the four games I have tried, none of them have even been signed. Disabling quarantine allows them to run anyway. I may try my hand at modifying the Gamejolt client and fixing the entitlements list tomorrow. If I am successful, I will send a pull request.

[Change Entitlements File](https://stackoverflow.com/a/31151323/6828099)
