### ISSUE TITLE
Gamejolt Client: The client does not detect when the game closes.

### ISSUE THREAD

**Issue by LucasWolschick** [gamejolt/gamejolt#38]
When using the client to play games, the client won't monitor the process and watch for it until it closes. Because of the programming of the client, you won't be able to play any other games, update any games (unless specified in the settings) until you close the client and reopen it.

**Steps to reproduce:**

1. Open the client
2. Install any game
3. Once installed, play the game
4. Exit it
5. See that the client still thinks the game is running.

**Comment by hworld** [comment]
Hey, this should be fixed with the latest client version.
