### ISSUE TITLE
Flash + HTML5 Web Builds Game's Iframe Bug

### ISSUE THREAD

**Issue by suntemple** [gamejolt/gamejolt#39]
This bug seems to occur when there are 2 web playable versions of the game available, in my case these were HTML5 + Flash. The Play button on the game cover opens an iframe with a broken link in this case and the game can not be played. It can still be played fine using the buttons on the release panel. I tried putting the Flash & HTML5 builds into separate releases but it didn't help. Even if they are in different releases the bug occurs anyway. As soon as I delete the Flash build from all releases, the game cover play button starts working fine.

Here is a screenshot which demonstrates the bug:
http://suntemple.co/gamejolt-html5-flash-iframe-bug.jpg
The game where the bug occured:
http://gamejolt.com/games/basket-ball/99795

**Comment by hworld** [comment]
This was fixed.
