### ISSUE TITLE
Unable to block some of the people from Gamejolt communities.

### ISSUE THREAD

**Issue by Animelici804** [gamejolt/gamejolt#456]
![It says this user does not exist.](https://user-images.githubusercontent.com/39384772/77741165-7d821780-7025-11ea-9a59-97de338a51b9.png)
It says this user does not exist, but actually, the user exists.
![image](https://user-images.githubusercontent.com/39384772/77741257-a60a1180-7025-11ea-997e-0a8b96da39ed.png)

**Comment by YLivay** [comment]
You block using the username, not the display name.
Thanks for the feedback, we should hook in our autocomplete to this field in the future :)
