### ISSUE TITLE
Image caching for offline mode.

### ISSUE THREAD

**Issue by MrStickmanPro1** [gamejolt/gamejolt#51]
A local image cache would be a great enhancement. Right now, images are not being displayed when offline. It could also help reduce page load times.

**Comment by hworld** [comment]
There should already be an image caching system in place, however it's not "smart" enough. It effectively saves the exact size of the image, and will only show if it's that same size. I think what would be better is to save a larger version for each game that we can always fallback to displaying for installed games.

**Comment by hworld** [comment]
We use a different repo for issue tracking. I've copied this ticket over there: https://github.com/gamejolt/issue-tracker/issues/703
