### ISSUE TITLE
Able to assign forum moderators to a channel you own

### ISSUE THREAD

**Issue by niksudan** [gamejolt/gamejolt#6]
Forum moderators should be able to perform the following:
- Able to sticky topics
- Able to lock topics
- Able to remove topics
- Able to remove topic posts
- Able to edit topic posts
- Able to mute a user from the channel
- Able to invite a user to the channel (if private)

You should be able to mute and mod users in similar fashion to the chat. Only the channel owner can mod/demod users.

**Comment by NikSudan** [comment]
![image](https://cloud.githubusercontent.com/assets/6004491/12271457/2076fbd8-b953-11e5-8ca9-3946ab7f2d5b.png)

Mod tools for topics and posts have been frontended
