### ISSUE TITLE
>:-/

### ISSUE THREAD

**Issue by hacknorris-notyetbanned** [gamejolt/gamejolt#759]
thanks :/
![screenshot](https://user-images.githubusercontent.com/74788012/111802561-6d1a1b00-88ce-11eb-9c19-cd0830b555ea.png)

**Comment by nilllzz** [comment]
If you want to report an issue, please do so on the [issue tracker](https://github.com/gamejolt/issue-tracker).

**Comment by hacknorris-notyetbanned** [comment]
bbb bruh...
