### ISSUE TITLE
Native Windows back button support

### ISSUE THREAD

**Issue by ghost** [gamejolt/gamejolt#77]
## Overview

I often use the GameJolt client on my Surface Pro 4 in tablet mode for convenience reasons, and instinctively use the back button, expecting it to navigate back a page when it does not. This functionality should be included in the GameJolt client

### Current behavior

Pressing the back button in tablet mode on the taskbar exits the app

### Expected behavior

Pressing the back button in tablet mode should navigate back, just like the in-app back button does.

### Additional info

[Here are the resources](https://msdn.microsoft.com/en-us/library/windows/apps/mt465734.aspx) for implementing the back button in UWP apps. This should be adaptable to this app somehow, because much of the UWP functionality is also available to Win32 apps, but I don't know the details. Perhaps something can be found [here](https://blogs.windows.com/buildingapps/2016/02/17/building-a-great-hosted-web-app/#rTi5PHTccdHVWLge.97)#

**Comment by hworld** [comment]
I kind of think this is fixed... I think it works with nwjs now since my mouse's back button works to navigate.
