### ISSUE TITLE
HTPC Options (force full screen, 10-foot user interface, etc)

### ISSUE THREAD

**Issue by diskotechjam** [gamejolt/gamejolt#82]
First of all. Wow. I absolutely love this. I just started using Game Jolt, so I'm excited there is an easy way to side-step having to download zips. 

I've noticed that the general design of the client is for use on a desktop, which is great for running on my laptop, but I do most of my gaming on my home theater PC. Is there a way to tweak the display settings to make the client a little more accomadating to this setup? For example, at the moment, I can't figure out a way to get the client to force games to launch in fullscreen. Or for that matter to automatically launch the client in fullscreen mode (maybe a command line option like --fullscreen could be used) Also, it would be nice in general if there were more options for a 10-foot user interface, such as simplified controller input or keyboard shortcuts, and a layout that was more focused on larger menus (In some ways I think the sidebar layout in the browser is actually more easy to navigate from the couch). Also, I can't figure out a way to get rid of the scrollbar on the right hand side.

Thanks again! This is really gonna be awesome, can't wait for the main release.

**Comment by YLivay** [comment]
Hey, really sorry for the slow response and thanks for the encouraging words :)
We usually don't check this repo for user submitted issues and suggestions, we have a [different repo](https://github.com/gamejolt/issue-tracker/issues) for this.

Forcing the games to work in fullscreen is sadly not a thing we think is possible for the client. every game has different methods of going fullscreen, theres no real standards and in fact passing command line arguments to some games may even break them! It is an interesting idea to have some sort of api games on GJ can use specifically to see if the user has any preferences, but even then i doubt it'll see much use. If you think it's still relevant you can re-open the issue on the issue tracker and we can discuss this further :)
