### ISSUE TITLE
Not seeing pictures, can't play video.

### ISSUE THREAD

**Issue by krso92** [gamejolt/gamejolt#85]
Hello, I am on current Linux version of client downloaded from gamejolt site and I do not see any pictures nor I can watch videos. Here is [screenshot](https://ibb.co/crm7Fa). I use Linux Mint 17.3 Rosa

**Comment by OffifialMITX** [comment]
Similar problem on my Debian 9 Dtretch, although I am able to watch videos.

**Comment by YLivay** [comment]
Sorry for the belated response, we don't use this repo for user submitted issues, please report them [here](https://github.com/gamejolt/issue-tracker/issues) in the future.

Anyways, this has been long resolved
