### ISSUE TITLE
My Unity WebGL game is not starting on GameJolt Client

### ISSUE THREAD

**Issue by ProGM** [gamejolt/gamejolt#89]
Hi!
I'm preparing my game page for a release on GameJolt. The game has an HTML5/WebGL version made with Unity.

The game runs correctly on browser from the GameJolt Website, both on chrome/safari/firefox, but it silently fails to start on the GameJolt Client.

The Unity loading bar fills completely, but then it just stops working.

I tried to enable the [debug mode of `nwjs`](https://github.com/nwjs/nw.js/wiki/debugging-with-devtools), by editing the `package.json`:

```
  "window": {
    ...
    "toolbar": true,
   ...
  }
```

So I could open the chromium console, and here's the output:
```
Flushing log file of length 29785 with 265 rows
2blob:http%3A//b-cdn.gamejolt.net/087f662a-eb45-4ad0-b36d-c8f03793783b:1 Uncaught TypeError: undefined is not a function
/Applications/Game Jolt Client.app/Contents/Resources/app.nw/node_modules/client-voodoo/build/commo…:67 Flushing log file of length 29785 with 265 rows
blob:http%3A//b-cdn.gamejolt.net/087f662a-eb45-4ad0-b36d-c8f03793783b:1 Uncaught TypeError: undefined is not a function
3/Applications/Game Jolt Client.app/Contents/Resources/app.nw/node_modules/client-voodoo/build/commo…:67 Flushing log file of length 29785 with 265 rows
blob:http%3A//b-cdn.gamejolt.net/087f662a-eb45-4ad0-b36d-c8f03793783b:1 Uncaught TypeError: undefined is not a function
3/Applications/Game Jolt Client.app/Contents/Resources/app.nw/node_modules/client-voodoo/build/commo…:67 Flushing log file of length 29785 with 265 rows
```

There are a few `TypeError`s during the game load, that seems to be the primary reason of failure.

P.S. I can share the game url privately, if you need it,  since the game is not yet out.

**Comment by YLivay** [comment]
Hey thanks for reporting, can you scroll down to the footer in the client and hit "send system report" right after trying to launch your game? I'll be able to see more info

**Comment by ProGM** [comment]
Hi @YLivay 
The game is now live, so you can test on your own client ;)

Just play the free demo ;D
http://gamejolt.com/games/little-briar-rose/253157

However, I've sent a report using the "send system report".

Thank you very much!

**Comment by YLivay** [comment]
Hey hey! Funny but this actually revealed another related bug with html games being considered "installable" by the client. Which package were you experiencing issues with, the webgl html one or the installable? Thanks for the quick response!

**Comment by ProGM** [comment]
LOL? Really?

The webgl html one is having issues.

Try to play it, you'll see that it fails to start after the loading process.
Instead it works in the GJ website

(the installable one are just fine ;) )

**Comment by YLivay** [comment]
Thanks, i'll look into it! It's very possible that after we finish the site rewrite we'll be able to push a completely new version of nwjs (it's what powers the client) that may solve the issue. If we won't be able to do that in a timely manner I guess we can redirect to the site to play it temporarily. Thanks for the input, this is very helpful.

**Comment by YLivay** [comment]
geez,  4 places to handle issues sure makes a mess of things.
This has been long resolved.
