### ISSUE TITLE
Order bug in old forum, should not "survive" on new forum

### ISSUE THREAD

**Issue by Tricky1975** [gamejolt/gamejolt#9]
![image](https://cloud.githubusercontent.com/assets/11202073/12232220/850849ae-b85d-11e5-9020-4de661455c6e.png)

The screenshot above shows what I mean. One thread was last touched 5 months ago and the next one only 1 day. Such things always confuse me. I deem it likely a spammer tried to spam that thread with a moderator deleting that post, or that the last post may have been marked for review, but that the ordering system still placed it up.

I think it's better that the ordering system actually orders on the date of the ACTUAL last post.

**Comment by NikSudan** [comment]
It screws up when the newest post is removed from a thread - the thread's last updated date isn't changed to the post prior to the deleted post. I'm sure this won't be a problem in the new forum, since it's being built from scratch.
