### ISSUE TITLE
Unable to locate json-loader dependency

### ISSUE THREAD

**Issue by niksudan** [gamejolt/gamejolt#91]
Tried to install and setup locally but couldn't get it working when visiting `http://localhost:8080`.

```
ERROR  Failed to compile with 1 errors

This dependency was not found:

* !json-loader!../translations/en_US/main.json in ./src/utils/translations.ts

To install it, you can run: npm install --save !json-loader!../translations/en_US/main.json
```

I've run `npm install --save !json-loader!../translations/en_US/main.json`, which just throws an error. I've also installed json-loader into `node_modules/` to no avail.

Running node v6.11.1 (npm v3.10.10) on macOS 10.12.4.

**Comment by hworld** [comment]
Oh run gulp translations:compile

**Comment by niksudan** [comment]
Update yo README, fool!
